<?php

/**
 * @file
 *
 * Handles the creation/display of islandora:sp-direct_input objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_direct_input_menu() {
  return array(
    'admin/islandora/direct_input' => array(
      'title' => 'direct input Module',
      'description' => 'Configure the direct input solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_direct_input_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}

/**
 * Implements hook_theme().
 */
function islandora_direct_input_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_direct_input' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-direct-input',
      'pattern' => 'islandora_direct_input__',
      'variables' => array('islandora_object' => NULL),
    )
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_direct_input_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_direct_input');
  // direct_input Content Model
  $direct_input_content_model = $connection->repository->constructObject('islandora:sp_direct_input');
  $direct_input_content_model->owner = 'fedoraAdmin';
  $direct_input_content_model->label = 'Islandora direct input Content Model';
  $direct_input_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $direct_input_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_direct_input_ds_composite_model.xml", FALSE);
  $direct_input_content_model->ingestDatastream($datastream);
  // direct input Collection
  $direct_input_collection = $connection->repository->constructObject('islandora:sp_direct_input_collection');
  $direct_input_collection->owner = 'fedoraAdmin';
  $direct_input_collection->label = 'direct input Collection';
  $direct_input_collection->models = 'islandora:collectionCModel';
  $direct_input_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream
  $datastream = $direct_input_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_direct_input_collection_policy.xml", FALSE);
  $direct_input_collection->ingestDatastream($datastream);
  // TN Datastream
  $datastream = $direct_input_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $direct_input_collection->ingestDatastream($datastream);
  return array(
    'islandora_direct_input' => array(
      'title' => 'Islandora direct input',
      'objects' => array(
        $direct_input_content_model,
        $direct_input_collection
      )
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_direct_input_islandora_sp_direct_input_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_direct_input', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */

function islandora_direct_input_islandora_sp_direct_input_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_direct_input', 'includes/derivatives');
  islandora_direct_input_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_direct_input_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_direct_input');
  return array(
    'direct input MODS form' => array(
      'form_file' => "$module_path/xml/islandora_direct_input_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_direct_input_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_direct_input_mods_form' => array(
      'content_model' => 'islandora:sp_direct_input',
      'form_name' => 'direct input MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_direct_input_islandora_sp_direct_input_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_direct_input_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_direct_input_direct_input_form',
      'module' => 'islandora_direct_input',
      'file' => 'includes/direct_input.form.inc'
    )
  );
}
